apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: elastic-cleanup-job
  namespace: elastic-cleanup 
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /opt/app-root/bin/python
            - /opt/app-root/src/delete-indices.py
            envFrom:
            - configMapRef:
                name: <if needed>
            - secretRef:
                name: <if needed>
            image: <def needed>
            imagePullPolicy: Always
            name: <image name>
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: "* /5 * * * *"
  successfulJobsHistoryLimit: 2
  suspend: false