apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: es-cleanup
  namespace: es-cleanup 
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          imagePullSecrets:
          - name: quay-cloudservices-pull
          containers:
          - command:
            - python
            - delete-indices.py
            image: quay.io/cloudservices/es-cleanup:latest
            imagePullPolicy: Always 
            env:
            - name: ES_HOSTNAME
              valueFrom:
                 secretKeyRef:
                    key: hostname 
                    name: es-cleanup-dev-secret
            name: es-cleanup 
            resources: 
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "500Mi"
                cpu: "500m"
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 2
  suspend: false
