apiVersion: v1
kind: Template
metadata:
  name: es-cleanup 
objects:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: es-cleanup
  spec:
    concurrencyPolicy: Allow
    failedJobsHistoryLimit: 3
    jobTemplate:
      metadata:
        creationTimestamp: null
      spec:
        template:
          metadata:
            creationTimestamp: null
          spec:
            imagePullSecrets:
            - name: quay-cloudservices-pull
            containers:
            - command:
              - python
              - delete-indices.py
              image: ${IMAGE}:${IMAGE_TAG}
              imagePullPolicy: Always 
              env:
              - name: ES_HOSTNAME
                valueFrom:
                  secretKeyRef:
                      key: hostname 
                      name: es-cleanup-secret
              name: es-cleanup 
              resources: 
                requests:
                  memory: "64Mi"
                  cpu: "50m"
                limits:
                  memory: "500Mi"
                  cpu: "500m"
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            restartPolicy: OnFailure
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
    schedule: "0 0 * * *"
    successfulJobsHistoryLimit: 2
    suspend: false
parameters:
- description: Image
  name: IMAGE
  value: quay.io/cloudservices/es-cleanup
  required: true
- description: Image tag
  name: IMAGE_TAG
  value: 4dd1da966d09
  required: true